### ISSUE TITLE
Ask for some detail about the Docrefine project of "Preunwarp" process 

### ISSUE THREAD

**Issue by evanlin88** [FelixHertlein/illtrtemplate-model#2]
Hello：

When I visit the website "https://felixhertlein.de/docrefine/about"

Can you tell me more detail about "Preunwarp: Fitting quadrilateral estimation around thesegmentation mask and homography warping."

Or  just meaning as shown in  "https://felixhertlein.github.io/illtrtemplate/#feng2021" Figure b
![20240509153336](https://github.com/FelixHertlein/illtrtemplate-model/assets/154392846/03c76324-4840-471d-b002-99b8e4f53ac2)

**Comment by FelixHertlein** [comment]
In the pre-unwarping stage, we try to find the corners of the document based on the binary mask of the document, associate the corners to a reference rectangle and then use a homography mapping to unwarp the image in such a way, that the detected corners are a the same position as the corners of the reference rectangle. In that way, coarse deformations such as translation, scaling, etc are removed, leaving only the fine-grained deformations.
In order to find the corners based on an outline, we maximize the IoU of a quadrilateral and the binary mask and then scale the estimated quadrilateral in small steps until the binary mask is entirely contained. See [here](https://github.com/FelixHertlein/contour-based-image-rectification/blob/main/src/contour_based_image_rectification/rectify.py#L99).

Regarding you question to the figure from our paper (full paper [here](https://openaccess.thecvf.com/content/ICCV2023W/NIVT/papers/Hertlein_Template-Guided_Illumination_Correction_for_Document_Images_with_Imperfect_Geometric_Reconstruction_ICCVW_2023_paper.pdf)):
Our approach integrates template images as depicted in (b). These images are simple RGB images with the expected layout of the document itself and must be provided in order to use our approach. The known a-priori information helps the model to to correctly remove the illumination artefacts. For more details about it, see our paper. If you have any specific question, please do not hesitate to ask.
